version: 2
jobs:
  build-and-publish:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - run:
          name: get fcct
          command: curl -o fcct https://github.com/coreos/fcct/releases/download/v0.6.0/fcct-x86_64-unknown-linux-gnu
      - run:
          name: transpile
          command: fcct --input base.fcc --pretty --output base.ign
      - run:
          name: publish
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_SHA1} ./base.ign

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-publish
          context: default
